spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${fint.application-id}
      key-deserializer: 'org.springframework.kafka.support.serializer.ErrorHandlingDeserializer'
      value-deserializer: 'org.springframework.kafka.support.serializer.ErrorHandlingDeserializer'
      properties:
        spring.deserializer.key.delegate.class: 'org.apache.kafka.common.serialization.StringDeserializer'
        spring.deserializer.value.delegate.class: 'org.springframework.kafka.support.serializer.JsonDeserializer'


logging:
  level:
    root: INFO
    no.fintlabs: DEBUG
    com.azure: WARN
    com.microsoft: WARN
    org.apache: WARN

fint:
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  org-id: fintlabs.no
  application-id: fint-kontroll-azure-ad-gateway
  kafka:
    default-replicas: 1
    application-id: ${fint.application-id}
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
      resources:
        resourcegrouptopic: resource-group
        resourcegroupmembertopic: resource-group-membership
  producer-max-message-size: 3145728
  consumer-max-message-size: 5242880
  consumer-partition-fetch-bytes: 3145728

  kontroll:
    azure-ad-gateway:
      user:
        #Set variable user Attributes. Case sensitive. See User Object in Graph
        employeeidattribute: onPremisesExtensionAttributes.extensionAttribute10
        studentidattribute: onPremisesExtensionAttributes.extensionAttribute9
        mainorgunitidattribute: extension_be2ffab7d262452b888aeb756f742377_MainOrgUnitId
        mainorgunitnameattribute: extension_be2ffab7d262452b888aeb756f742377_MainOrgUnitName
        externaluserattribute: state
        externaluservalue: frid
      group:
        fintkontrollidattribute: extension_be2ffab7d262452b888aeb756f742377_FintKontrollRoleId
        prefix: "-pre-"
        suffix: "-suff-"
      group-scheduler:
        pull:
          initial-delay-ms: 1000
          delta-delay-ms: 600000
      user-scheduler:
        pull:
          initial-delay-ms: 2000
          fixed-delay-ms: 500000
        refresh:
          interval-ms: 518400000

#placeholders. Do not add creds
azure:
  credentials:
    clientid: XXXX
    clientsecret: XXXX
    tenantguid: XXXX
    entobjectid: ZZZZ
