spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${fint.application-id}

logging:
  level:
    root: INFO

fint:
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  org-id: fintlabs.no
  application-id: fint-kontroll-azure-ad-gateway
  kafka:
    default-replicas: 1
    application-id: ${fint.application-id}
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
      resources:
        resourcegrouptopic: resource-group
        resourcegroupmembertopic: resource-group-membership
        azureuserproducertopic: azureuser

  kontroll:
    azure-ad-gateway:
      users:
        #Set employeeID and studentID Attributes. Case sensitive. See User Object in Graph
        employeeidattribute: onPremisesExtensionAttributes.extensionAttribute10
        studentidattribute: onPremisesExtensionAttributes.extensionAttribute9
      group-scheduler:
        pull:
          initial-delay-ms: 1000
          delta-delay-ms: 600000
      user-scheduler:
        pull:
          initial-delay-ms: 2000
          fixed-delay-ms: 500000
        refresh:
          interval-ms: 518400000

#placeholders. Do not add creds
azure:
  credentials:
    clientid:   XXXX
    clientsecret: XXXX
    tenantguid: XXXX
    entobjectid: ZZZZ


