spring:
  profiles:
    include:
      - kafka

server:
  port: 8080

logging:
  level:
    root: INFO
    no.fintlabs: INFO
    no.fintlabs.cache.ehcache: WARN
    com.azure: WARN
    com.microsoft: WARN
    org.apache: WARN
    org.springframework.web.servlet.DispatcherServlet: WARN

fint:
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 20000000
  application-id: fint-kontroll-azure-ad-gateway

  kontroll:
    azure-ad-gateway:
      user:
        #Set variable user Attributes. Case sensitive. See User Object in Graph
        employeeidattribute: onPremisesExtensionAttributes.extensionAttribute10
        studentidattribute: onPremisesExtensionAttributes.extensionAttribute9
        mainorgunitidattribute: extension_be2ffab7d262452b888aeb756f742377_MainOrgUnitId
        mainorgunitnameattribute: extension_be2ffab7d262452b888aeb756f742377_MainOrgUnitName
        externaluserattribute: onPremisesExtensionAttributes.extensionAttribute11
        externaluservalue: novari
        userpagingsize: 999
      group:
        fintkontrollidattribute: extension_be2ffab7d262452b888aeb756f742377_FintKontrollRoleId
        prefix: "-pre-"
        suffix: "-suff-"
        allowgroupupdate: false
        allowgroupdelete: false
        uniquenameprefix: "FKRID"
        grouppagingsize: 999
      group-scheduler:
        pull:
          initial-delay-ms: 5000
          delta-delay-ms: 600000
        delta-pull:
          initial-delay-ms: 5000
          delta-delay-ms: 600000
        clear-cache: "0 0 23 ? * SUN"

      user-scheduler:
        pull:
          initial-delay-ms: 1000
          fixed-delay-ms: 450000
        refresh:
          interval-ms: 518400000

#placeholders. Do not add creds
azure:
  timeout: 1
  credentials:
    clientid: XXXX
    clientsecret: XXXX
    tenantguid: XXXX
    entobjectid: ZZZZ
