logging:
  level:
    root: INFO
    com.azure: WARN
    com.microsoft: WARN
    org.apache: WARN
    no.fintlabs: INFO
    no.fintlabs.cache.ehcache: WARN
    okhttp3: WARN
    #org.apache: ERROR

fint:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${fint.application-id}

#server:
  #port: 8085