logging:
  level:
    root: INFO
    com.azure: WARN
    com.microsoft: WARN
    org.apache: WARN
    no.fintlabs: INFO
    no.fintlabs.cache.ehcache: WARN
    okhttp3: WARN
    #org.apache: ERROR
fint:
  kontroll:
    azure-ad-gateway:
      user-scheduler:
        pull:
          initial-delay-ms: 1000
          fixed-delay-ms: 30000
        clear-cache: "0 30 */2 * * *"
      group-scheduler:
        pull:
          initial-delay-ms: 5000
          delta-delay-ms: 20000
        delta-pull:
          initial-delay-ms: 5000
          delta-delay-ms: 20000
        clear-cache: "0 0 */2 * * *"
#fint:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: ${fint.application-id}

#server:
  #port: 8085