spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  fint:
    application-id: fint-kontroll-azure-ad-gateway
logging:
  level:
    root: INFO

fint:
  application-id: fint-kontroll-azure-ad-gateway
  kafka:
    application-id: ${fint.application-id}
  flyt:
    azure-ad-gateway:
      resources:
        pull:
          initial-delay-ms: 5000
          fixed-delay-ms: 900000
        refresh:
          interval-ms: 518400000

azurecredentials:
  clientid: XXXX
  clientsecret: XXXX
  tenantguid: XXXX