spring:
  profiles:
    include:
      - kafka
      - db

server:
  port: 8080

logging:
  pattern:
    console: "%d{dd.MM.yyyy HH:mm:ss.SSSXXX} %highlight(%-5level) %logger{0} - %msg%n"
  level:
    root: INFO
    no.fintlabs: INFO
    com.azure: WARN
    com.microsoft: WARN
    org.apache: WARN
    org.springframework.web.servlet.DispatcherServlet: WARN

fint:
  application-id: fint-kontroll-azure-ad-gateway

  kontroll:
    azure-ad-gateway:
      user:
        #Set variable user Attributes. Case sensitive. See User Object in Graph
        employeeidattribute: onPremisesExtensionAttributes.extensionAttribute10
        studentidattribute: onPremisesExtensionAttributes.extensionAttribute9
        mainorgunitidattribute: extension_be2ffab7d262452b888aeb756f742377_MainOrgUnitId
        mainorgunitnameattribute: extension_be2ffab7d262452b888aeb756f742377_MainOrgUnitName
        enableexternalusers: false
        externaluserattribute: onPremisesExtensionAttributes.extensionAttribute11
        externaluservalue: ----
        userpagingsize: 999
      group:
        fintkontrollidattribute: extension_be2ffab7d262452b888aeb756f742377_FintKontrollRoleId
        prefix: "-pre-"
        suffix: "-suff-"
        allowgroupupdate: false
        allowgroupdelete: false
        uniquenameprefix: ----
        grouppagingsize: 999
      group-scheduler:
        pull:
          initial-delay-ms: 5000
          delta-delay-ms: 600000
        delta-pull:
          quickstart: false #no full download of all groups and members initially on startup. Listens on /groups/delta?$deltatoken=latest
          initial-delay-ms: 5000
          delta-delay-ms: 600000
        clear-cache: "0 0 23 ? * SUN"

      user-scheduler:
        pull:
          initial-delay-ms: 1000
          fixed-delay-ms: 450000
        refresh:
          interval-ms: 518400000
        clear-cache: "0 0 23 ? * SUN"

#placeholders. Do not add creds
#azure:
#  timeout: 1
#  credentials:
#    clientid: XXXX
#    clientsecret: XXXX
#    tenantguid: XXXX
#    entobjectid: ZZZZ
