logging:
  level:
    root: INFO
    com.azure: DEBUG
    com.microsoft: DEBUG
    no.fintlabs: DEBUG
    #org.apache: ERROR

fint:
  org-id: fintlabs.no
  application-id: fint-kontroll-azure-ad-gateway
  kafka:
    default-replicas: 1
    bootstrap-servers: localhost:9092
#    application-id: ${fint.application-id}
    consumer:
      group-id: ${fint.application-id}
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll

server:
  port: 8085