apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-azure-ad-gateway
  app.kubernetes.io/instance: fint-kontroll-azure-ad-gateway_fintlabs-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: add
        path: "/spec/env/-"
        value:
          name: "fint.kafka.topic.org-id"
          value: "fintlabs-no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "fintlabs-no.kontroll.entity.azure*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "fintlabs-no.kontroll.entity.azure*"
      - op: replace
        path: "/spec/kafka/acls/2/topic"
        value: "fintlabs-no.kontroll.entity.resource-group*"

    target:
      kind: Application
      name: fint-kontroll-azure-ad-gateway
  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-beta-vault/items/kontroll-azure-ad-gateway-fintlabs"
    target:
      kind: OnePasswordItem
      name: fint-kontroll-azure-ad-gateway