apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-azure-ad-gateway
  app.kubernetes.io/instance: fint-kontroll-azure-ad-gateway_bfk-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: bfk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "bfk.no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "bfk-no.kontroll.entity.azure*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "bfk-no.kontroll.entity.azure*"
      - op: replace
        path: "/spec/kafka/acls/2/topic"
        value: "bfk-no.kontroll.entity.resource-group*"
    target:
      kind: Application
      name: fint-kontroll-azure-ad-gateway
  - patch: |-
      - op: replace
        path: "/spec/itemPath"
        value: "vaults/aks-api-vault/items/kontroll-bfk-azure-ad-gateway"
    target:
      kind: OnePasswordItem
      name: fint-kontroll-azure-ad-gateway