apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-azure-ad-gateway
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-azure-ad-gateway:latest
  imagePullPolicy: Always
  env: []
  envFrom:
    - secretRef:
        name: fint-kontroll-azure-ad-gateway

  kafka:
    enabled: true
    #orgId: fintlabs-no
    acls:
      - topic: 'placeholder-fintlabs-no.kontroll.*'
        permission: read
      - topic: 'placeholder-fintlabs-no.kontroll.*'
        permission: admin
      - topic: 'placeholder-fintlabs-no.kontroll.entity.resource-group*'
        permission: read